[custom_php_settings]
# 1. 动态性能调优示例
upload_max_filesize = 100M
post_max_size = 100M
memory_limit = 512M
max_execution_time = 300

# 2. 动态加载扩展示例（如果镜像里已经编译但默认没开启，或者你动态追加了.so文件）
# extension=intl
# extension=mongodb
# extension=swoole

# 3. 开启 Opcache 缓存优化（生产环境必备）
opcache.enable=1
opcache.memory_consumption=128
opcache.max_accelerated_files=10000