services:
  web:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/jetsung/nginx-php:8.2
    container_name: php-nginx-app
    restart: always
    ports:
      - "81:80"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./web:/var/www/html          # 挂载代码
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # 挂载Nginx配置
      
      # 🔥 核心新增：将自定义的 ini 配置文件挂载到 PHP 的配置扫描目录下
      - ./php_conf/custom.ini:/usr/local/etc/php/conf.d/z_custom.ini:ro
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"